export type BuiltInCatalogKind='movie'|'series';
export type BuiltInCatalogCategory='Discovery'|'Editorial'|'Genres'|'Moods'|'Premium & World';
export type BuiltInCatalogDefinition={id:string;title:string;kind:BuiltInCatalogKind;category:BuiltInCatalogCategory;featured?:boolean;tmdbPath?:string};

function defs(kind:BuiltInCatalogKind,rows:Array<[string,string,BuiltInCatalogCategory,boolean?,string?]>):BuiltInCatalogDefinition[]{
  return rows.map(([id,title,category,featured=false,tmdbPath])=>({id:`${kind==='movie'?'movie':'show'}:${id}`,title,kind,category,featured,tmdbPath}));
}

export const movieCatalogs=defs('movie',[
['popular-movies','Popular Movies','Discovery',true,'/movie/popular?language=en-US'],['trending-movies','Trending Movies','Discovery',true,'/trending/movie/day?language=en-US'],['most-watched-movies','Most Watched Movies','Discovery',true],['most-anticipated-movies','Most Anticipated Movies','Discovery',true,'/movie/upcoming?language=en-US&region=US'],['top-rated-movies','Top Rated Movies','Discovery',true,'/movie/top_rated?language=en-US'],['imdb-top-movies','IMDb Top Movies','Discovery',true],['trakt-trending-movies','Trakt Trending Movies','Discovery',true],['trakt-popular-movies','Trakt Popular Movies','Discovery',true],['trakt-most-watched-movies','Trakt Most Watched Movies','Discovery'],['trakt-most-collected-movies','Trakt Most Collected Movies','Discovery'],
['new-releases','New Releases','Editorial',true,'/movie/now_playing?language=en-US&region=US'],['now-playing','Now Playing','Editorial',true,'/movie/now_playing?language=en-US&region=US'],['coming-soon','Coming Soon','Editorial',true,'/movie/upcoming?language=en-US&region=US'],['weekend-box-office','Weekend Box Office','Editorial',true],['best-of-2026','Best of 2026','Editorial',true],['best-of-2025','Best of 2025','Editorial'],['critics-favorites','Critics Favorites','Editorial'],['audience-favorites','Audience Favorites','Editorial'],['award-winners','Award Winners','Editorial'],['oscar-winners','Oscar Winners','Editorial'],['golden-globe-winners','Golden Globe Winners','Editorial'],['cannes-favorites','Cannes Favorites','Editorial'],['sundance-favorites','Sundance Favorites','Editorial'],['hidden-gems','Hidden Gems','Editorial'],['cult-classics','Cult Classics','Editorial'],
['action-essentials','Action Essentials','Genres',false,'/discover/movie?with_genres=28&sort_by=popularity.desc&include_adult=false&language=en-US'],['adventure-movies','Adventure Movies','Genres',false,'/discover/movie?with_genres=12&sort_by=popularity.desc&language=en-US'],['animation-favorites','Animation Favorites','Genres',false,'/discover/movie?with_genres=16&sort_by=popularity.desc&language=en-US'],['comedy-hits','Comedy Hits','Genres',false,'/discover/movie?with_genres=35&sort_by=popularity.desc&language=en-US'],['crime-movies','Crime Movies','Genres',false,'/discover/movie?with_genres=80&sort_by=popularity.desc&language=en-US'],['documentaries','Documentaries','Genres',false,'/discover/movie?with_genres=99&sort_by=vote_average.desc&vote_count.gte=100&language=en-US'],['drama-essentials','Drama Essentials','Genres',false,'/discover/movie?with_genres=18&sort_by=popularity.desc&language=en-US'],['family-night','Family Night','Genres',false,'/discover/movie?with_genres=10751&sort_by=popularity.desc&language=en-US'],['fantasy-worlds','Fantasy Worlds','Genres',false,'/discover/movie?with_genres=14&sort_by=popularity.desc&language=en-US'],['horror-hits','Horror Hits','Genres',false,'/discover/movie?with_genres=27&sort_by=popularity.desc&language=en-US'],['mystery-movies','Mystery Movies','Genres',false,'/discover/movie?with_genres=9648&sort_by=popularity.desc&language=en-US'],['romance-favorites','Romance Favorites','Genres',false,'/discover/movie?with_genres=10749&sort_by=popularity.desc&language=en-US'],['sci-fi-essentials','Sci-Fi Essentials','Genres',false,'/discover/movie?with_genres=878&sort_by=popularity.desc&language=en-US'],['thriller-picks','Thriller Picks','Genres',false,'/discover/movie?with_genres=53&sort_by=popularity.desc&language=en-US'],['war-movies','War Movies','Genres',false,'/discover/movie?with_genres=10752&sort_by=popularity.desc&language=en-US'],['western-classics','Western Classics','Genres',false,'/discover/movie?with_genres=37&sort_by=popularity.desc&language=en-US'],['superhero-movies','Superhero Movies','Genres'],['martial-arts','Martial Arts','Genres'],['heist-movies','Heist Movies','Genres'],['spy-movies','Spy Movies','Genres'],['disaster-movies','Disaster Movies','Genres'],['survival-stories','Survival Stories','Genres'],['post-apocalyptic','Post-Apocalyptic','Genres'],['time-travel','Time Travel','Genres'],['mind-benders','Mind-Benders','Genres'],
['psychological-thrillers','Psychological Thrillers','Moods'],['true-stories','True Stories','Moods'],['biopics','Biopics','Moods'],['sports-movies','Sports Movies','Moods'],['music-movies','Music Movies','Moods'],['christmas-movies','Christmas Movies','Moods'],['halloween-movies','Halloween Movies','Moods'],['summer-blockbusters','Summer Blockbusters','Moods'],['feel-good-movies','Feel-Good Movies','Moods'],['comfort-movies','Comfort Movies','Moods'],['date-night','Date Night','Moods'],['girls-night','Girls Night','Moods'],['guys-night','Guys Night','Moods'],['under-90-minutes','Under 90 Minutes','Moods'],['epic-movies','Epic Movies','Moods'],
['4k-hdr-showcase','4K/HDR Showcase','Premium & World',true],['dolby-vision-picks','Dolby Vision Picks','Premium & World'],['atmos-showcase','Atmos Showcase','Premium & World'],['international-cinema','International Cinema','Premium & World'],['korean-movies','Korean Movies','Premium & World'],['japanese-movies','Japanese Movies','Premium & World'],['indian-cinema','Indian Cinema','Premium & World'],['french-cinema','French Cinema','Premium & World'],['spanish-language-movies','Spanish-Language Movies','Premium & World'],['anime-movies','Anime Movies','Premium & World']
]);

export const tvCatalogs=defs('series',[
['popular-shows','Popular Shows','Discovery',true,'/tv/popular?language=en-US'],['trending-shows','Trending Shows','Discovery',true,'/trending/tv/day?language=en-US'],['most-watched-shows','Most Watched Shows','Discovery',true],['most-anticipated-shows','Most Anticipated Shows','Discovery',true],['top-rated-shows','Top Rated Shows','Discovery',true,'/tv/top_rated?language=en-US'],['imdb-top-shows','IMDb Top Shows','Discovery',true],['trakt-trending-shows','Trakt Trending Shows','Discovery',true],['trakt-popular-shows','Trakt Popular Shows','Discovery',true],['trakt-most-watched-shows','Trakt Most Watched Shows','Discovery'],['trakt-most-collected-shows','Trakt Most Collected Shows','Discovery'],
['new-series','New Series','Editorial',true],['new-episodes','New Episodes','Editorial',true,'/tv/on_the_air?language=en-US'],['airing-today','Airing Today','Editorial',true,'/tv/airing_today?language=en-US'],['on-the-air','On the Air','Editorial',true,'/tv/on_the_air?language=en-US'],['best-of-2026-tv','Best of 2026 TV','Editorial',true],['best-of-2025-tv','Best of 2025 TV','Editorial'],['critics-favorites-tv','Critics Favorites TV','Editorial'],['audience-favorites-tv','Audience Favorites TV','Editorial'],['emmy-winners','Emmy Winners','Editorial'],['golden-globe-tv-winners','Golden Globe TV Winners','Editorial'],['prestige-drama','Prestige Drama','Editorial'],['binge-worthy','Binge-Worthy','Editorial'],['hidden-gem-series','Hidden Gem Series','Editorial'],['cult-tv','Cult TV','Editorial'],['limited-series','Limited Series','Editorial'],
['action-series','Action Series','Genres',false,'/discover/tv?with_genres=10759&sort_by=popularity.desc&language=en-US'],['adventure-series','Adventure Series','Genres',false,'/discover/tv?with_genres=10759&sort_by=popularity.desc&language=en-US'],['animated-series','Animated Series','Genres',false,'/discover/tv?with_genres=16&sort_by=popularity.desc&language=en-US'],['comedy-series','Comedy Series','Genres',false,'/discover/tv?with_genres=35&sort_by=popularity.desc&language=en-US'],['crime-series','Crime Series','Genres',false,'/discover/tv?with_genres=80&sort_by=popularity.desc&language=en-US'],['documentary-series','Documentary Series','Genres',false,'/discover/tv?with_genres=99&sort_by=popularity.desc&language=en-US'],['drama-series','Drama Series','Genres',false,'/discover/tv?with_genres=18&sort_by=popularity.desc&language=en-US'],['family-series','Family Series','Genres',false,'/discover/tv?with_genres=10751&sort_by=popularity.desc&language=en-US'],['fantasy-series','Fantasy Series','Genres',false,'/discover/tv?with_genres=10765&sort_by=popularity.desc&language=en-US'],['horror-series','Horror Series','Genres'],['mystery-series','Mystery Series','Genres',false,'/discover/tv?with_genres=9648&sort_by=popularity.desc&language=en-US'],['romance-series','Romance Series','Genres'],['sci-fi-series','Sci-Fi Series','Genres',false,'/discover/tv?with_genres=10765&sort_by=popularity.desc&language=en-US'],['thriller-series','Thriller Series','Genres'],['war-series','War Series','Genres',false,'/discover/tv?with_genres=10768&sort_by=popularity.desc&language=en-US'],['western-series','Western Series','Genres',false,'/discover/tv?with_genres=37&sort_by=popularity.desc&language=en-US'],['superhero-series','Superhero Series','Genres'],['martial-arts-series','Martial Arts Series','Genres'],['heist-series','Heist Series','Genres'],['spy-series','Spy Series','Genres'],['survival-series','Survival Series','Genres'],['post-apocalyptic-series','Post-Apocalyptic Series','Genres'],['time-travel-series','Time Travel Series','Genres'],['mind-bending-series','Mind-Bending Series','Genres'],['psychological-series','Psychological Series','Genres'],
['true-crime','True Crime','Moods'],['true-story-series','True Story Series','Moods'],['biographical-series','Biographical Series','Moods'],['sports-series','Sports Series','Moods'],['music-series','Music Series','Moods'],['reality-favorites','Reality Favorites','Moods'],['competition-shows','Competition Shows','Moods'],['game-shows','Game Shows','Moods'],['talk-shows','Talk Shows','Moods'],['late-night','Late Night','Moods'],['food-cooking','Food & Cooking','Moods'],['home-design','Home & Design','Moods'],['travel-series','Travel Series','Moods'],['nature-series','Nature Series','Moods'],['science-series','Science Series','Moods'],
['kids-tv','Kids TV','Premium & World',true],['teen-series','Teen Series','Premium & World'],['k-dramas','K-Dramas','Premium & World'],['japanese-series','Japanese Series','Premium & World'],['anime-series','Anime Series','Premium & World',true],['british-tv','British TV','Premium & World'],['nordic-noir','Nordic Noir','Premium & World'],['spanish-language-tv','Spanish-Language TV','Premium & World'],['indian-series','Indian Series','Premium & World'],['international-tv','International TV','Premium & World']
]);

if(movieCatalogs.length!==75||tvCatalogs.length!==75)throw new Error(`Built-in catalog registry must contain 75 movies and 75 TV shows; got ${movieCatalogs.length}/${tvCatalogs.length}`);
export const allBuiltInCatalogs=[...movieCatalogs,...tvCatalogs];
export const featuredBuiltInCatalogs=(kind:BuiltInCatalogKind,limit=6)=>(kind==='movie'?movieCatalogs:tvCatalogs).filter(x=>x.featured).slice(0,limit);
