android.useAndroidX=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
ASTRAWAVE_FIREBASE_API_KEY=AIzaSyDoQ35kpsWeVGI99SNYeLiwWMoV-Rk0FvA
ASTRAWAVE_FIREBASE_APP_ID=1:1053104069475:android:7a00e70c7edcb7e3f81156
ASTRAWAVE_FIREBASE_PROJECT_ID=astrawave
ASTRAWAVE_FIREBASE_SENDER_ID=1053104069475
